doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        proxy_namespace: Proxies
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        default_entity_manager: default
        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml # Set to xml in case of XML mapping
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Entity'
                alias: App
            ApplicationSonataUserBundle: ~
            ApplicationSonataMediaBundle: ~
            SonataMediaBundle: ~