fos_user:
  db_driver:      orm # can be orm or odm
  firewall_name:  main

  service:
    user_manager: sonata.user.orm.user_manager

  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_user%"

  #user_class:     Sonata\UserBundle\Entity\BaseUser
  user_class:     App\Application\Sonata\UserBundle\Entity\User

  group:
    #group_class:   Sonata\UserBundle\Entity\BaseGroup
    #group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
    group_class:   App\Application\Sonata\UserBundle\Entity\Group