sonata_admin:
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css

sonata_block:
    blocks:
        sonata_translation.block.locale_switcher: ~

sonata_translation:
    locales: [en, pl, fr, it, nl, es]
    default_locale: en
    # here enable the types you need
    gedmo:
        enabled: true
    knplabs:
        enabled: true
